---
- name: Deploy React App and Backend with Docker
  hosts: webserver
  become: yes
  tasks:
    - name: Update the system
      yum:
        name: "*"
        state: latest

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start and enable Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: true

    - name: Start React App Container
      docker_container:
        name: meineReactApp
        image: sophieischenkots/counter
        ports:
          - "80:80"
        state: started
    