---
- name: Deploy React App and Backend with Docker
  hosts: webserver
  become: yes
  vars: 
    docker_image_tag: "{{ lookup('env', 'GITHUB_SHA') }}"
  tasks:
    - name: Update the system
      yum:
        name: "*"
        state: latest

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start and enable Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: true

    - name: Pull Frontend Docker image from Docker Hub
      community.docker.docker_image:
        name: "sophieischenkots"
        tag: "{{ docker_image_tag }}"
        source: pull

    - name: Run Frontend Docker container
      community.docker.docker_container:
        name: react-counter
        image: "sophieischenkots/counter:{{ docker_image_tag }}"
        state: started
        restart_policy: always
        published_ports:
          - "80:80"
    
